# Generated by Django 4.2.7 on 2023-12-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firemation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firewall_ip',
            field=models.CharField(default='0.0.0.0/0', max_length=255),
        ),
    ]
