# Generated by Django 4.2.7 on 2023-12-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firemation_app', '0002_user_firewall_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firewall_vendor',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
