# Generated by Django 4.2.7 on 2024-01-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firemation_app', '0004_firewall_remove_user_firewall_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
